### ISSUE TITLE
Affect.throw not being tested

### ISSUE THREAD

**Issue by amsross** [Risto-Stevcev/bs-effects#1]
The `fail` in `Affect.throw` is the error that is thrown.

For example, the message for the error that is being checked for is `"Async effect should have failed"`, rather than something from `Fs.read_file_sync` like `"ENOENT: no such file or directory, open 'non-existent-name'"`.

https://github.com/Risto-Stevcev/bs-effects/blob/079a4cf367c06cb41177819bd3c2cf65858b662c/test/Test_Affect.re#L94-L101

edit: This appears to be covering up the fact that there's nothing actually happening in this test.

**Comment by Risto-Stevcev** [comment]
Hi @amsross   ,

Thanks for the PR, and sorry for any inconvenience my delay in communication may have caused. I'm no longer maintaining my Bucklescript repositories, I've been meaning to archive them. Feel free to fork the repo.

Risto
